### ISSUE TITLE
.jl suffix

### ISSUE THREAD

**Issue by tshort** [JuliaWGPU/WGPUCanvas.jl#1]
For consistency with Julia packages, I'd add a `.jl` ending to the repository name. It also helps when searching for Julia packages.

**Comment by arhik** [comment]
@tshort Thank you. I am also thinking to rename it to `WGPUCanvas.jl`. Please suggest. All CAPS is also not recommended; `JuliaRegistrator` doesn't like it.

**Comment by tshort** [comment]
WGPUCanvas.jl looks good to me.

**Comment by arhik** [comment]
Done
